// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Bookings.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createNewBookings = `-- name: CreateNewBookings :one

insert into bookings (
    ID,pet_id ,user_id,start_date,end_date,status,created_at
)values(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, pet_id, user_id, start_date, end_date, status, created_at
`

type CreateNewBookingsParams struct {
	ID        uuid.UUID
	PetID     uuid.UUID
	UserID    uuid.UUID
	StartDate time.Time
	EndDate   time.Time
	Status    BookingStatus
	CreatedAt sql.NullTime
}

func (q *Queries) CreateNewBookings(ctx context.Context, arg CreateNewBookingsParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createNewBookings,
		arg.ID,
		arg.PetID,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.CreatedAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.PetID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec

DELETE from bookings where ID = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBooking, id)
	return err
}

const getBooking = `-- name: GetBooking :one

SELECT start_date,end_date,status,created_at from bookings where ID = $1
`

type GetBookingRow struct {
	StartDate time.Time
	EndDate   time.Time
	Status    BookingStatus
	CreatedAt sql.NullTime
}

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (GetBookingRow, error) {
	row := q.db.QueryRowContext(ctx, getBooking, id)
	var i GetBookingRow
	err := row.Scan(
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getBookingByStatus = `-- name: GetBookingByStatus :many

SELECT b.start_date,b.end_date,b.status,b.created_at,p.nama as nama_hewan,u.nama as nama_users 
from bookings b INNER JOIN pets p on pet_id = p.ID 
INNER JOIN users u on user_id = u.ID
where b.status = $1
ORDER BY b.start_date ASC
OFFSET $2 LIMIT $3
`

type GetBookingByStatusParams struct {
	Status BookingStatus
	Offset int32
	Limit  int32
}

type GetBookingByStatusRow struct {
	StartDate time.Time
	EndDate   time.Time
	Status    BookingStatus
	CreatedAt sql.NullTime
	NamaHewan string
	NamaUsers string
}

func (q *Queries) GetBookingByStatus(ctx context.Context, arg GetBookingByStatusParams) ([]GetBookingByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookingByStatus, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookingByStatusRow
	for rows.Next() {
		var i GetBookingByStatusRow
		if err := rows.Scan(
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
			&i.NamaHewan,
			&i.NamaUsers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByUserID = `-- name: GetBookingByUserID :one

SELECT ID,pet_id ,user_id,status FROM bookings where ID = $1 and user_id=$2
`

type GetBookingByUserIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetBookingByUserIDRow struct {
	ID     uuid.UUID
	PetID  uuid.UUID
	UserID uuid.UUID
	Status BookingStatus
}

func (q *Queries) GetBookingByUserID(ctx context.Context, arg GetBookingByUserIDParams) (GetBookingByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBookingByUserID, arg.ID, arg.UserID)
	var i GetBookingByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.PetID,
		&i.UserID,
		&i.Status,
	)
	return i, err
}

const updateBookings = `-- name: UpdateBookings :one
update bookings SET start_date = $1,end_date = $2,status = $3 where ID = $4
RETURNING id, pet_id, user_id, start_date, end_date, status, created_at
`

type UpdateBookingsParams struct {
	StartDate time.Time
	EndDate   time.Time
	Status    BookingStatus
	ID        uuid.UUID
}

func (q *Queries) UpdateBookings(ctx context.Context, arg UpdateBookingsParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBookings,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.ID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.PetID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
