// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Message.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one

insert into message (
     ID,bookings_id,sender_id,receiver_id,message,is_read,created_at
)values (
    $1,$2,$3,$4,$5,$6,$7
)
RETURNING id, bookings_id, sender_id, receiver_id, message, is_read, created_at
`

type CreateMessageParams struct {
	ID         uuid.UUID
	BookingsID uuid.UUID
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
	Message    string
	IsRead     bool
	CreatedAt  sql.NullTime
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.BookingsID,
		arg.SenderID,
		arg.ReceiverID,
		arg.Message,
		arg.IsRead,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.BookingsID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE from message where ID = $1 and sender_id = $2
`

type DeleteMessageParams struct {
	ID       uuid.UUID
	SenderID uuid.UUID
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, arg.ID, arg.SenderID)
	return err
}

const getChatInbox = `-- name: GetChatInbox :many
SELECT bookings_id, sender_id, receiver_id, message, is_read, created_at, nama_hewan FROM(
    SELECT DISTINCT ON(bookings_id)
    m.bookings_id,
    m.sender_id,
    m.receiver_id,
    m.message,
    m.is_read,
    m.created_at,
    p.nama as nama_hewan FROM message m INNER JOIN bookings b on bookings_id = b.ID
    INNER JOIN pets p on b.pet_id = p.ID WHERE m.sender_id = $1 OR m.receiver_id =$1 ORDER BY m.bookings_id,m.created_at DESC
)as subquery
ORDER BY created_at DESC
OFFSET $2 LIMIT $3
`

type GetChatInboxParams struct {
	SenderID uuid.UUID
	Offset   int32
	Limit    int32
}

type GetChatInboxRow struct {
	BookingsID uuid.UUID
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
	Message    string
	IsRead     bool
	CreatedAt  sql.NullTime
	NamaHewan  string
}

func (q *Queries) GetChatInbox(ctx context.Context, arg GetChatInboxParams) ([]GetChatInboxRow, error) {
	rows, err := q.db.QueryContext(ctx, getChatInbox, arg.SenderID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatInboxRow
	for rows.Next() {
		var i GetChatInboxRow
		if err := rows.Scan(
			&i.BookingsID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
			&i.NamaHewan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistoryPesan = `-- name: GetHistoryPesan :many
SELECT 
    m.id, m.message, m.is_read, m.created_at, m.sender_id,
    u_sender.nama as pengirim_nama
FROM message m 
INNER JOIN users u_sender on m.sender_id = u_sender.ID
WHERE m.bookings_id = $1
ORDER BY m.created_at ASC
OFFSET $2 LIMIT $3
`

type GetHistoryPesanParams struct {
	BookingsID uuid.UUID
	Offset     int32
	Limit      int32
}

type GetHistoryPesanRow struct {
	ID           uuid.UUID
	Message      string
	IsRead       bool
	CreatedAt    sql.NullTime
	SenderID     uuid.UUID
	PengirimNama string
}

func (q *Queries) GetHistoryPesan(ctx context.Context, arg GetHistoryPesanParams) ([]GetHistoryPesanRow, error) {
	rows, err := q.db.QueryContext(ctx, getHistoryPesan, arg.BookingsID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHistoryPesanRow
	for rows.Next() {
		var i GetHistoryPesanRow
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
			&i.SenderID,
			&i.PengirimNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagebyIDuser = `-- name: GetMessagebyIDuser :one

SELECT ID,bookings_id,sender_id,receiver_id,message from message where sender_id = $1
`

type GetMessagebyIDuserRow struct {
	ID         uuid.UUID
	BookingsID uuid.UUID
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
	Message    string
}

func (q *Queries) GetMessagebyIDuser(ctx context.Context, senderID uuid.UUID) (GetMessagebyIDuserRow, error) {
	row := q.db.QueryRowContext(ctx, getMessagebyIDuser, senderID)
	var i GetMessagebyIDuserRow
	err := row.Scan(
		&i.ID,
		&i.BookingsID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Message,
	)
	return i, err
}

const markMessageAsRead = `-- name: MarkMessageAsRead :exec
update message set is_read = true where bookings_id= $1 and sender_id = $2 and is_read = false
`

type MarkMessageAsReadParams struct {
	BookingsID uuid.UUID
	SenderID   uuid.UUID
}

func (q *Queries) MarkMessageAsRead(ctx context.Context, arg MarkMessageAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markMessageAsRead, arg.BookingsID, arg.SenderID)
	return err
}
