// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type BookingStatus string

const (
	BookingStatusPENDING  BookingStatus = "PENDING"
	BookingStatusAPPROVED BookingStatus = "APPROVED"
	BookingStatusDONE     BookingStatus = "DONE"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus
	Valid         bool // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type Conds string

const (
	CondsMakan    Conds = "makan"
	CondsSehat    Conds = "sehat"
	CondsSakit    Conds = "sakit"
	CondsGrooming Conds = "grooming"
)

func (e *Conds) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Conds(s)
	case string:
		*e = Conds(s)
	default:
		return fmt.Errorf("unsupported scan type for Conds: %T", src)
	}
	return nil
}

type NullConds struct {
	Conds Conds
	Valid bool // Valid is true if Conds is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConds) Scan(value interface{}) error {
	if value == nil {
		ns.Conds, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Conds.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConds) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Conds), nil
}

type Kelamin string

const (
	KelaminJantan Kelamin = "Jantan"
	KelaminBetina Kelamin = "Betina"
)

func (e *Kelamin) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Kelamin(s)
	case string:
		*e = Kelamin(s)
	default:
		return fmt.Errorf("unsupported scan type for Kelamin: %T", src)
	}
	return nil
}

type NullKelamin struct {
	Kelamin Kelamin
	Valid   bool // Valid is true if Kelamin is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKelamin) Scan(value interface{}) error {
	if value == nil {
		ns.Kelamin, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Kelamin.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKelamin) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Kelamin), nil
}

type Role string

const (
	RoleUser  Role = "User"
	RoleStaff Role = "Staff"
	RoleAdmin Role = "Admin"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Booking struct {
	ID        uuid.UUID
	PetID     uuid.UUID
	UserID    uuid.UUID
	StartDate time.Time
	EndDate   time.Time
	Status    BookingStatus
	CreatedAt sql.NullTime
}

type Message struct {
	ID         uuid.UUID
	BookingsID uuid.UUID
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
	Message    string
	IsRead     bool
	CreatedAt  sql.NullTime
}

type Notification struct {
	ID        uuid.UUID
	IDUser    uuid.UUID
	Title     sql.NullString
	Message   string
	CreatedAt sql.NullTime
	IsRead    sql.NullBool
}

type Pet struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Nama         string
	Jenis        string
	Age          sql.NullInt32
	CreatedAt    sql.NullTime
	Catatan      sql.NullString
	Berat        sql.NullString
	JenisKelamin Kelamin
	Ras          sql.NullString
	IsVaxinated  sql.NullBool
	PhotoPath    sql.NullString
}

type PetStatusLog struct {
	ID         uuid.UUID
	IDBookings uuid.UUID
	Status     Conds
	Note       sql.NullString
	PhotoPath  sql.NullString
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
	EditedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Nama      string
	Password  string
	Email     string
	Role      Role
	CreatedAt sql.NullTime
}
