// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Notifications.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUnreadNotifictaions = `-- name: CountUnreadNotifictaions :exec
SELECT COUNT(*) FROM Notifications where is_read = false and id_user =$1
`

func (q *Queries) CountUnreadNotifictaions(ctx context.Context, idUser uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, countUnreadNotifictaions, idUser)
	return err
}

const createNotifications = `-- name: CreateNotifications :one
insert INTO Notifications(
    ID,id_user,title,message,created_at 
)values(
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, id_user, title, message, created_at, is_read
`

type CreateNotificationsParams struct {
	ID        uuid.UUID
	IDUser    uuid.UUID
	Title     sql.NullString
	Message   string
	CreatedAt sql.NullTime
}

func (q *Queries) CreateNotifications(ctx context.Context, arg CreateNotificationsParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotifications,
		arg.ID,
		arg.IDUser,
		arg.Title,
		arg.Message,
		arg.CreatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.Title,
		&i.Message,
		&i.CreatedAt,
		&i.IsRead,
	)
	return i, err
}

const deleteNotifications = `-- name: DeleteNotifications :exec
DELETE from Notifications where ID = $1
`

func (q *Queries) DeleteNotifications(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotifications, id)
	return err
}

const getHistoryNotifications = `-- name: GetHistoryNotifications :many
SELECT title,message,created_at from Notifications where id_user = $1
ORDER BY created_at DESC OFFSET $2 LIMIT $3
`

type GetHistoryNotificationsParams struct {
	IDUser uuid.UUID
	Offset int32
	Limit  int32
}

type GetHistoryNotificationsRow struct {
	Title     sql.NullString
	Message   string
	CreatedAt sql.NullTime
}

func (q *Queries) GetHistoryNotifications(ctx context.Context, arg GetHistoryNotificationsParams) ([]GetHistoryNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getHistoryNotifications, arg.IDUser, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHistoryNotificationsRow
	for rows.Next() {
		var i GetHistoryNotificationsRow
		if err := rows.Scan(&i.Title, &i.Message, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotifications = `-- name: GetNotifications :one
SELECT title,message,created_at from Notifications where ID = $1
`

type GetNotificationsRow struct {
	Title     sql.NullString
	Message   string
	CreatedAt sql.NullTime
}

func (q *Queries) GetNotifications(ctx context.Context, id uuid.UUID) (GetNotificationsRow, error) {
	row := q.db.QueryRowContext(ctx, getNotifications, id)
	var i GetNotificationsRow
	err := row.Scan(&i.Title, &i.Message, &i.CreatedAt)
	return i, err
}

const markNotificationsaAsRead = `-- name: MarkNotificationsaAsRead :exec
Update Notifications Set is_read = true where ID = $1 and is_read = false
`

func (q *Queries) MarkNotificationsaAsRead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markNotificationsaAsRead, id)
	return err
}

const updateNotification = `-- name: UpdateNotification :one
Update Notifications set title = $1,message = $2 where ID = $3
RETURNING id, id_user, title, message, created_at, is_read
`

type UpdateNotificationParams struct {
	Title   sql.NullString
	Message string
	ID      uuid.UUID
}

func (q *Queries) UpdateNotification(ctx context.Context, arg UpdateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, updateNotification, arg.Title, arg.Message, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.Title,
		&i.Message,
		&i.CreatedAt,
		&i.IsRead,
	)
	return i, err
}
