// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: PetStatus.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createNewLog = `-- name: CreateNewLog :one

Insert into pet_status_log(
    ID,id_bookings,status,note,photo_path,created_by,created_at,edited_at
) values (
    $1,$2,$3,$4,$5,$6,$7,$8
)
RETURNING id, id_bookings, status, note, photo_path, created_by, created_at, edited_at
`

type CreateNewLogParams struct {
	ID         uuid.UUID
	IDBookings uuid.UUID
	Status     Conds
	Note       sql.NullString
	PhotoPath  sql.NullString
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
	EditedAt   time.Time
}

func (q *Queries) CreateNewLog(ctx context.Context, arg CreateNewLogParams) (PetStatusLog, error) {
	row := q.db.QueryRowContext(ctx, createNewLog,
		arg.ID,
		arg.IDBookings,
		arg.Status,
		arg.Note,
		arg.PhotoPath,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.EditedAt,
	)
	var i PetStatusLog
	err := row.Scan(
		&i.ID,
		&i.IDBookings,
		&i.Status,
		&i.Note,
		&i.PhotoPath,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const deleteLog = `-- name: DeleteLog :exec
DELETE from pet_status_log where ID = $1
`

func (q *Queries) DeleteLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLog, id)
	return err
}

const getAllLog = `-- name: GetAllLog :many
SELECT ps.status,ps.note,ps.photo_path,ps.created_by,ps.created_at,ps.edited_at,p.nama as nama_hewan, u.nama as nama_users from pet_status_log ps 
INNER JOIN bookings b on ps.id_bookings = b.ID 
INNER JOIN pets p on b.pet_id = p.ID
INNER JOIN users u on b.user_id = u.ID
where u.ID = $1
ORDER BY ps.created_at DESC
OFFSET $2 LIMIT $3
`

type GetAllLogParams struct {
	ID     uuid.UUID
	Offset int32
	Limit  int32
}

type GetAllLogRow struct {
	Status    Conds
	Note      sql.NullString
	PhotoPath sql.NullString
	CreatedBy uuid.UUID
	CreatedAt time.Time
	EditedAt  time.Time
	NamaHewan string
	NamaUsers string
}

func (q *Queries) GetAllLog(ctx context.Context, arg GetAllLogParams) ([]GetAllLogRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllLog, arg.ID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLogRow
	for rows.Next() {
		var i GetAllLogRow
		if err := rows.Scan(
			&i.Status,
			&i.Note,
			&i.PhotoPath,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.EditedAt,
			&i.NamaHewan,
			&i.NamaUsers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLOgbyIDbooking = `-- name: GetLOgbyIDbooking :one
SELECT id_bookings,status FROM pet_status_log where id_bookings = $1
`

type GetLOgbyIDbookingRow struct {
	IDBookings uuid.UUID
	Status     Conds
}

func (q *Queries) GetLOgbyIDbooking(ctx context.Context, idBookings uuid.UUID) (GetLOgbyIDbookingRow, error) {
	row := q.db.QueryRowContext(ctx, getLOgbyIDbooking, idBookings)
	var i GetLOgbyIDbookingRow
	err := row.Scan(&i.IDBookings, &i.Status)
	return i, err
}

const getLog = `-- name: GetLog :one

SELECT psl.status,psl.note,psl.photo_path,psl.created_by,psl.created_at,psl.edited_at,p.nama as nama_hewan, p.jenis as jenis_hewan from pet_status_log psl 
INNER JOIN bookings b on psl.id_bookings = b.ID 
INNER JOIN pets p on b.pet_id = p.ID
where psl.id_bookings = $1
`

type GetLogRow struct {
	Status     Conds
	Note       sql.NullString
	PhotoPath  sql.NullString
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
	EditedAt   time.Time
	NamaHewan  string
	JenisHewan string
}

func (q *Queries) GetLog(ctx context.Context, idBookings uuid.UUID) (GetLogRow, error) {
	row := q.db.QueryRowContext(ctx, getLog, idBookings)
	var i GetLogRow
	err := row.Scan(
		&i.Status,
		&i.Note,
		&i.PhotoPath,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EditedAt,
		&i.NamaHewan,
		&i.JenisHewan,
	)
	return i, err
}

const updateLog = `-- name: UpdateLog :one
update pet_status_log set status = $1, note = $2, photo_path = $3,edited_at = $4 where ID = $5
RETURNING id, id_bookings, status, note, photo_path, created_by, created_at, edited_at
`

type UpdateLogParams struct {
	Status    Conds
	Note      sql.NullString
	PhotoPath sql.NullString
	EditedAt  time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateLog(ctx context.Context, arg UpdateLogParams) (PetStatusLog, error) {
	row := q.db.QueryRowContext(ctx, updateLog,
		arg.Status,
		arg.Note,
		arg.PhotoPath,
		arg.EditedAt,
		arg.ID,
	)
	var i PetStatusLog
	err := row.Scan(
		&i.ID,
		&i.IDBookings,
		&i.Status,
		&i.Note,
		&i.PhotoPath,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}
