// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Pets.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPets = `-- name: CreatePets :one

Insert into pets(
    ID,user_id,nama,Jenis,age,created_at
) values (
    $1,$2,$3,$4,$5,$6
    )
RETURNING id, user_id, nama, jenis, age, created_at
`

type CreatePetsParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Nama      string
	Jenis     string
	Age       sql.NullInt32
	CreatedAt sql.NullTime
}

func (q *Queries) CreatePets(ctx context.Context, arg CreatePetsParams) (Pet, error) {
	row := q.db.QueryRowContext(ctx, createPets,
		arg.ID,
		arg.UserID,
		arg.Nama,
		arg.Jenis,
		arg.Age,
		arg.CreatedAt,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.Jenis,
		&i.Age,
		&i.CreatedAt,
	)
	return i, err
}

const deletePets = `-- name: DeletePets :exec

DELETE from pets where ID = $1 and user_id = $2
`

type DeletePetsParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePets(ctx context.Context, arg DeletePetsParams) error {
	_, err := q.db.ExecContext(ctx, deletePets, arg.ID, arg.UserID)
	return err
}

const getPetsID = `-- name: GetPetsID :one
Select nama,Jenis,age,user_id,ID from pets where ID = $1
`

type GetPetsIDRow struct {
	Nama   string
	Jenis  string
	Age    sql.NullInt32
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetPetsID(ctx context.Context, id uuid.UUID) (GetPetsIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPetsID, id)
	var i GetPetsIDRow
	err := row.Scan(
		&i.Nama,
		&i.Jenis,
		&i.Age,
		&i.UserID,
		&i.ID,
	)
	return i, err
}

const getPetsMany = `-- name: GetPetsMany :many

SELECT p.nama, p.jenis, p.age, u.nama AS owner_name FROM pets p INNER JOIN users u ON p.user_id = u.ID
ORDER BY p.created_at DESC
OFFSET $1 LIMIT $2
`

type GetPetsManyParams struct {
	Offset int32
	Limit  int32
}

type GetPetsManyRow struct {
	Nama      string
	Jenis     string
	Age       sql.NullInt32
	OwnerName string
}

func (q *Queries) GetPetsMany(ctx context.Context, arg GetPetsManyParams) ([]GetPetsManyRow, error) {
	rows, err := q.db.QueryContext(ctx, getPetsMany, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPetsManyRow
	for rows.Next() {
		var i GetPetsManyRow
		if err := rows.Scan(
			&i.Nama,
			&i.Jenis,
			&i.Age,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePets = `-- name: UpdatePets :one
update pets set nama = $1, jenis = $2, age = $3, created_at = $4 where ID = $5 and user_id = $6
RETURNING id, user_id, nama, jenis, age, created_at
`

type UpdatePetsParams struct {
	Nama      string
	Jenis     string
	Age       sql.NullInt32
	CreatedAt sql.NullTime
	ID        uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) UpdatePets(ctx context.Context, arg UpdatePetsParams) (Pet, error) {
	row := q.db.QueryRowContext(ctx, updatePets,
		arg.Nama,
		arg.Jenis,
		arg.Age,
		arg.CreatedAt,
		arg.ID,
		arg.UserID,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.Jenis,
		&i.Age,
		&i.CreatedAt,
	)
	return i, err
}
