// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Pets.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPets = `-- name: CreatePets :one

Insert into pets(
    ID,user_id,nama,Jenis,age,created_at,catatan,berat,jenis_kelamin,ras,is_vaxinated,photo_path
) values (
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12
    )
RETURNING id, user_id, nama, jenis, age, created_at, catatan, berat, jenis_kelamin, ras, is_vaxinated, photo_path
`

type CreatePetsParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Nama         string
	Jenis        string
	Age          sql.NullInt32
	CreatedAt    sql.NullTime
	Catatan      string
	Berat        string
	JenisKelamin Kelamin
	Ras          string
	IsVaxinated  bool
	PhotoPath    string
}

func (q *Queries) CreatePets(ctx context.Context, arg CreatePetsParams) (Pet, error) {
	row := q.db.QueryRowContext(ctx, createPets,
		arg.ID,
		arg.UserID,
		arg.Nama,
		arg.Jenis,
		arg.Age,
		arg.CreatedAt,
		arg.Catatan,
		arg.Berat,
		arg.JenisKelamin,
		arg.Ras,
		arg.IsVaxinated,
		arg.PhotoPath,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.Jenis,
		&i.Age,
		&i.CreatedAt,
		&i.Catatan,
		&i.Berat,
		&i.JenisKelamin,
		&i.Ras,
		&i.IsVaxinated,
		&i.PhotoPath,
	)
	return i, err
}

const deletePets = `-- name: DeletePets :exec

DELETE from pets where ID = $1 and user_id = $2
`

type DeletePetsParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePets(ctx context.Context, arg DeletePetsParams) error {
	_, err := q.db.ExecContext(ctx, deletePets, arg.ID, arg.UserID)
	return err
}

const getPetsByID = `-- name: GetPetsByID :one

SELECT id FROM pets WHERE id = $1 AND user_id = $2
`

type GetPetsByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPetsByID(ctx context.Context, arg GetPetsByIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getPetsByID, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPetsDetail = `-- name: GetPetsDetail :one
Select p.nama,p.jenis,p.age,p.ID,p.catatan,p.berat,p.jenis_kelamin,p.ras,p.is_vaxinated,p.photo_path,u.nama 
from pets p INNER JOIN users U ON U.ID = p.user_id where P.ID = $1
`

type GetPetsDetailRow struct {
	Nama         string
	Jenis        string
	Age          sql.NullInt32
	ID           uuid.UUID
	Catatan      string
	Berat        string
	JenisKelamin Kelamin
	Ras          string
	IsVaxinated  bool
	PhotoPath    string
	Nama_2       string
}

func (q *Queries) GetPetsDetail(ctx context.Context, id uuid.UUID) (GetPetsDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getPetsDetail, id)
	var i GetPetsDetailRow
	err := row.Scan(
		&i.Nama,
		&i.Jenis,
		&i.Age,
		&i.ID,
		&i.Catatan,
		&i.Berat,
		&i.JenisKelamin,
		&i.Ras,
		&i.IsVaxinated,
		&i.PhotoPath,
		&i.Nama_2,
	)
	return i, err
}

const getPetsListSt = `-- name: GetPetsListSt :many
SELECT p.nama, p.jenis,u.nama AS owner_name FROM pets p INNER JOIN users u ON p.user_id = u.ID
ORDER BY p.created_at DESC
OFFSET $1 LIMIT $2
`

type GetPetsListStParams struct {
	Offset int32
	Limit  int32
}

type GetPetsListStRow struct {
	Nama      string
	Jenis     string
	OwnerName string
}

func (q *Queries) GetPetsListSt(ctx context.Context, arg GetPetsListStParams) ([]GetPetsListStRow, error) {
	rows, err := q.db.QueryContext(ctx, getPetsListSt, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPetsListStRow
	for rows.Next() {
		var i GetPetsListStRow
		if err := rows.Scan(&i.Nama, &i.Jenis, &i.OwnerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPetsListUser = `-- name: GetPetsListUser :many
Select nama,jenis,age,ID from pets where user_id = $1 ORDER by created_at DESC OFFSET $2 LIMIT $3
`

type GetPetsListUserParams struct {
	UserID uuid.UUID
	Offset int32
	Limit  int32
}

type GetPetsListUserRow struct {
	Nama  string
	Jenis string
	Age   sql.NullInt32
	ID    uuid.UUID
}

func (q *Queries) GetPetsListUser(ctx context.Context, arg GetPetsListUserParams) ([]GetPetsListUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPetsListUser, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPetsListUserRow
	for rows.Next() {
		var i GetPetsListUserRow
		if err := rows.Scan(
			&i.Nama,
			&i.Jenis,
			&i.Age,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePets = `-- name: UpdatePets :one
update pets set nama = $1, jenis = $2, age = $3,catatan = $4,berat =$5,jenis_kelamin =$6,ras=$7,is_vaxinated = $8,photo_path = $9 where ID = $10 and user_id = $11
RETURNING id, user_id, nama, jenis, age, created_at, catatan, berat, jenis_kelamin, ras, is_vaxinated, photo_path
`

type UpdatePetsParams struct {
	Nama         string
	Jenis        string
	Age          sql.NullInt32
	Catatan      string
	Berat        string
	JenisKelamin Kelamin
	Ras          string
	IsVaxinated  bool
	PhotoPath    string
	ID           uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) UpdatePets(ctx context.Context, arg UpdatePetsParams) (Pet, error) {
	row := q.db.QueryRowContext(ctx, updatePets,
		arg.Nama,
		arg.Jenis,
		arg.Age,
		arg.Catatan,
		arg.Berat,
		arg.JenisKelamin,
		arg.Ras,
		arg.IsVaxinated,
		arg.PhotoPath,
		arg.ID,
		arg.UserID,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.Jenis,
		&i.Age,
		&i.CreatedAt,
		&i.Catatan,
		&i.Berat,
		&i.JenisKelamin,
		&i.Ras,
		&i.IsVaxinated,
		&i.PhotoPath,
	)
	return i, err
}
