// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: User.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
Select COUNT(*) from users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one

Insert into users (
    ID,nama,password,email,role,created_at 
)values(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)

RETURNING id, nama, password, email, role, created_at
`

type CreateUserParams struct {
	ID        uuid.UUID
	Nama      string
	Password  string
	Email     string
	Role      Role
	CreatedAt sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Nama,
		arg.Password,
		arg.Email,
		arg.Role,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Password,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec

DELETE from  users where ID = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserID = `-- name: GetUserID :one

Select nama,password,email,role from  users where ID = $1
`

type GetUserIDRow struct {
	Nama     string
	Password string
	Email    string
	Role     Role
}

func (q *Queries) GetUserID(ctx context.Context, id uuid.UUID) (GetUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserID, id)
	var i GetUserIDRow
	err := row.Scan(
		&i.Nama,
		&i.Password,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const getUseremail = `-- name: GetUseremail :one

Select ID,nama,password,email,role from  users where email = $1
`

type GetUseremailRow struct {
	ID       uuid.UUID
	Nama     string
	Password string
	Email    string
	Role     Role
}

func (q *Queries) GetUseremail(ctx context.Context, email string) (GetUseremailRow, error) {
	row := q.db.QueryRowContext(ctx, getUseremail, email)
	var i GetUseremailRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Password,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const listsUser = `-- name: ListsUser :many

Select nama,password,email,role,created_at  from  users order by created_at desc limit $1 offset $2
`

type ListsUserParams struct {
	Limit  int32
	Offset int32
}

type ListsUserRow struct {
	Nama      string
	Password  string
	Email     string
	Role      Role
	CreatedAt sql.NullTime
}

func (q *Queries) ListsUser(ctx context.Context, arg ListsUserParams) ([]ListsUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listsUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListsUserRow
	for rows.Next() {
		var i ListsUserRow
		if err := rows.Scan(
			&i.Nama,
			&i.Password,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one

update users set nama = $1, password = $2, email = $3, role = $4 where ID = $5
RETURNING id, nama, password, email, role, created_at
`

type UpdateUserParams struct {
	Nama     string
	Password string
	Email    string
	Role     Role
	ID       uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Nama,
		arg.Password,
		arg.Email,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Password,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
